{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agence-immobiliere.fullname" . }}-frontend-config
  labels:
    {{- include "agence-immobiliere.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
