{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agence-immobiliere.fullname" . }}-mongodb-secrets
  labels:
    {{- include "agence-immobiliere.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | default "change-me-in-production" | quote }}
{{- end }}
