{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agence-immobiliere.fullname" . }}-mongodb
  labels:
    {{- include "agence-immobiliere.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  selector:
    {{- include "agence-immobiliere.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agence-immobiliere.fullname" . }}-mongodb-headless
  labels:
    {{- include "agence-immobiliere.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27017
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  selector:
    {{- include "agence-immobiliere.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
