{{- if .Values.persistence.uploads.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agence-immobiliere.fullname" . }}-uploads
  labels:
    {{- include "agence-immobiliere.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- range .Values.persistence.uploads.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
